Person#toString(): update result message
se-edu/addressbook-level4 pull request #1028
Opened 2020-12-07 05:27 UTC by jonahtanjz

Fixes #453.

Update result message with ";" as delimiters and omit "Tags:" if it is not present.

2020-12-10 05:54 UTC, damithc commented
@Zhiyuan-Amos any chance you can review this PR too?

2020-12-10 06:38 UTC, Zhiyuan-Amos commented
Hi @jonahtanjz! Thanks for submitting this PR, and I'm just quickly reviewing this. Based on our [Commit Organization Convention](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#commit-organization):

> Each commit contains a single logical change

Your commit consists of 2 changes, namely:
1. Remove "Tags:" when user did not input any tags.
2. Add delimiter.

So you should break up your changes into 2 separate commits. To do so, you might have to familiarise yourself with some of the more advanced git commands such as `git reset`. :)

---

Sidenote: Your changes could have been accepted already if it's for other open source projects (or maybe even at work, depending on the engineering practices of the company), but this project is more particular about coding standards etc because it's used by students to learn Software Engineering :)

2020-12-10 06:47 UTC, Zhiyuan-Amos requested changes

2020-12-10 06:47 UTC, Zhiyuan-Amos commented on src/main/java/seedu/address/model/person/Person.java
> +        if (getTags().size() > 0) {
1. Assign `getTags` to a variable. See https://github.com/se-edu/addressbook-level4/pull/1026#discussion_r535838362. Also, in this scenario, the code will be creating an unmodifiable wrapper of `tags` twice, which is unnecessary.

1. Can we use `isEmpty()` instead? It's a more concise version of `getTags().size() > 0`.

2020-12-11 06:20 UTC, jonahtanjz commented on src/main/java/seedu/address/model/person/Person.java
> +        if (getTags().size() > 0) {
Alright thanks. I've made the changes.

2020-12-11 06:24 UTC, jonahtanjz commented
Thanks @damithc and @Zhiyuan-Amos for the comments. I've separated the commits and made the suggested changes.

2020-12-11 08:22 UTC, Zhiyuan-Amos requested changes
Few more comments:

1. There should be another newline after the commit title. Based on the post by `canihasreview` https://github.com/se-edu/addressbook-level4/pull/1028#issuecomment-743001299, you should only be seeing:

```
[v2 1/2] Person: Add delimiters to result message
[v2 2/2] Person: Remove 'Tags: ' if there are no tags
```

2. For the 2nd paragraph of your commit messages, remove the phrase `As a result`. Based on our commit organisation docs, it's already known that the 2nd paragraph is about the consequences of the 1st paragraph, so there's no need for this phrase.

You can amend commit messages using interactive rebase and force pushing afterwards.

---

Just some minor nits before we can have this merged!

2020-12-11 08:22 UTC, Zhiyuan-Amos commented on src/main/java/seedu/address/model/person/Person.java
> +        tags.forEach(builder::append);
I think the following is more intuitive:

```
Set<Tag> tags = getTags();
if (!tags.isEmpty()) {
    builder.append("; Tags: ");
    tags.forEach(builder::append);
}
```

Because it can be understood as: "If tags exist, add the header `; Tags: ` followed by the corresponding tags." Rather than calling `tags.forEach(builder::append);` regardless of whether the tags exist.

What do you think? :)

2020-12-11 11:39 UTC, j-lum commented
@jonahtanjz Remember to submit a new iteration when you're ready.

2020-12-11 16:02 UTC, jonahtanjz commented on src/main/java/seedu/address/model/person/Person.java
> +        tags.forEach(builder::append);
Yes this seems a lot more intuitive as `tags.forEach(builder::append);` should not be called if `tags` is empty.

2020-12-11 16:03 UTC, jonahtanjz commented
Thanks @Zhiyuan-Amos. I have updated the commit message and made the changes.
Thanks @j-lum for the reminder.

2020-12-11 21:34 UTC, Zhiyuan-Amos approved these changes
LGTM! @damithc

2020-12-12 06:34 UTC, merged

2020-12-12 06:35 UTC, damithc commented
Thanks @jonahtanjz for the PR and @Zhiyuan-Amos for the meticulous review. 👍